### ISSUE TITLE
 It cannot run because two classes cannot be found.

### ISSUE THREAD

**Issue by ldlywt** [ruslin-note/ruslin-android#45]
import uniffi.ruslin.MarkdownTagRange
import uniffi.ruslin.parseMarkdown

![image](https://github.com/ruslin-note/ruslin-android/assets/17981095/a220dc3b-41f3-42b6-8d0a-0623c9f53050)

**Comment by DianQK** [comment]
I have added some build instructions in the PR #46. The missing Kotlin code is generated by `uniffi-rs`, so you need to build the Rust part first.
