### ISSUE TITLE
Deserialize error on sync

### ISSUE THREAD

**Issue by ghost** [ruslin-note/ruslin-android#51]
Hi, I am getting this error when trying to sync my notes:
```
09-02 19:20:39 UTC [INFO]: starting the delete remote content task
09-02 19:20:39 UTC [INFO]: starting the upload local content task
09-02 19:20:39 UTC [INFO]: starting the delta remote content task from context: None
09-02 19:20:40 UTC [WARN]: skip unsupported type: 1023c75660fe4ab9bccb248a44cc1283
09-02 19:20:40 UTC [WARN]: skip unsupported type: e87701fb4b0c491abb2c7f5cb3d8cf29
09-02 19:20:40 UTC [WARN]: skip unsupported type: 822bfa66719646cf94d5985fdcf5c020
09-02 19:20:40 UTC [WARN]: skip unsupported type: edd296c7779c49828eec153629688f47
09-02 19:20:40 UTC [WARN]: skip unsupported type: 3432e03cd59a4cf2b3192a37d6fc3121
09-02 19:20:41 UTC [WARN]: skip unsupported type: 8459e3de6c6944b6bcb10fb5bf18948c
09-02 19:20:41 UTC [WARN]: skip unsupported type: 95bd919692584cf997561ee3bc06301b
09-02 19:20:41 UTC [WARN]: skip unsupported type: 3927ab46086449cdb0704c81d9ed0a30
09-02 19:20:41 UTC [WARN]: skip unsupported type: 8e78cab2b43447f693a59f8aa4813a2e
09-02 19:20:41 UTC [WARN]: skip unsupported type: 619f56121485450890da5a77837f4231
09-02 19:20:41 UTC [ERROR]: sync error: deserialize error: order -> 158695568374.59375
```

**Comment by DianQK** [comment]
Could ypu provider your joplin and joplin server version?

**Comment by SandResidence** [comment]
Sure!
Ruslin android version: 0.1.1-beta.2
Joplin version on PC: **2.11.11** (prod, Linux)
Joplin server: joplin/server Docker image (digest: 8b83d1ee0a39) so it is **2.12.1-beta**

**Comment by DianQK** [comment]
joplin seems to use the timestamp as the value of order, and I don't think it makes sense to use decimals here. 
So I am going to convert 158695568374.59375 to 158695568374. This may modify your data. Let me know if you don't like this.

One possible workaround is that you can manually adjust the order of this this note, which may change the order to a normal value.

**Comment by SandResidence** [comment]
What about saving the data?
If Joplin expects a value of "158695568374.59375" and Ruslin passes it "158695568374," the Joplin server will assume that this is a new note and therefore the note will be duplicated with a different ID.

**Comment by DianQK** [comment]
> What about saving the data?
> If Joplin expects a value of "158695568374.59375" and Ruslin passes it "158695568374," the Joplin server will assume that this is a new note and therefore the note will be duplicated with a different ID.

Notes are not copied. If you don't modify this note, this "order" data will not be updated to the joplin server.

> Edit: Wouldn't a better solution be to change the "int" type to "float" to follow the types provided by Joplin?

Yes, you're right.

**Comment by DianQK** [comment]
Joplin still seems to use integer, I think this should be fixed to integer using a script.
