### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ruslin-note/ruslin-android#66]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7755382382#L1422

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/9ed1a9c7c9821fd856a1a80453aa747444a7c651

**Comment by linsui** [comment]
I thought this is mostly caused by NDK version mismatch.

**Comment by licaon-kter** [comment]
My diffoscope run did not finish yet... :)

**Comment by linsui** [comment]
[org.dianqk.ruslin_1000.apk.html.zip](https://github.com/user-attachments/files/16897864/org.dianqk.ruslin_1000.apk.html.zip)

**Comment by DianQK** [comment]
I'll submit a PR to fix it. :)

**Comment by DianQK** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15704 should fix the issue.
